### ISSUE TITLE
My account is upset because i have a several transactions that didn't go through and i can't claim my wise.

### ISSUE THREAD

**Issue by Jrnyman66** [wise-foundation/wise-website-bug-reports#10]
I had been claiming wisetokens on 12/22/20. I ran into a problem when the token purchases locked up but did not give me a reason. I went back and tried to cancel them and now my account is all messed up and i can't claim my tokens. Please advise me what to do?

**Comment by coffee-converter** [comment]
Try resetting metamask in its advanced settings section...then try claiming again.

**Comment by Jrnyman66** [comment]
Wow! It worked! Thank you very, VERY much!

**Comment by coffee-converter** [comment]
No problem.  This is the first thing to try whenever metamask seems in a weird state.
