### ISSUE TITLE
[BUG] **Claim wise tokens button does not load 

### ISSUE THREAD

**Issue by lgutierrez11** [wise-foundation/wise-website-bug-reports#12]
**Describe the bug**
When I go on to the wisetoken.net website, and attempt to claim my wise tokens, nothing happens when I click on the Claim Wise Token Button. It shows that it is loading and takes me to the metamask screen where I confirm the gas price and hit enter. And after I click on claim wise tokens it shows that it is loading but stays frozen on that screen for over 10 minutes. If I let it sit until the end, it just takes me back to the previous screen. What can I do to resolve this issue?
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lukovicky** [comment]
I have the same problem. My claim wise tokens button does not load. Please, if someone could explain this problem to me, I would appreciate it very much, as I am not very experienced with computers and cryptos (same problem as user Igutierrez11). Thanks a lot!

**Comment by coffee-converter** [comment]
@lgutierrez11 @Lukovicky 

Try first resetting metamask within its advanced settings screen.  Then try the claim again, confirm w/ metamask, then let me know if a new transaction shows up on your address in etherscan.

**Comment by lgutierrez11** [comment]
I reset Metamask and continued to try without any success. I finally tried a different browser and it worked immediately. Thank you for all your help! If this doesn’t work for anyone having the same issue after restarting mega mask, try from a different internet browser!

**Comment by Lukovicky** [comment]
> @lgutierrez11 @Lukovicky
> 
> Try first resetting metamask within its advanced settings screen. Then try the claim again, confirm w/ metamask, then let me know if a new transaction shows up on your address in etherscan.

Thanks a lot! It worked..but I'm not sure if the transaction showed up in etherscan (I don't know where my adress is)

**Comment by coffee-converter** [comment]
> > @lgutierrez11 @Lukovicky
> > Try first resetting metamask within its advanced settings screen. Then try the claim again, confirm w/ metamask, then let me know if a new transaction shows up on your address in etherscan.
> 
> Thanks a lot! It worked..but I'm not sure if the transaction showed up in etherscan (I don't know where my adress is)

Your address is in your metamask wallet.  You can also get a link to etherscan by clicking on the transaction in the activity section of metamask, then finding a little arrow icon.
