### ISSUE TITLE
[FEATURE] **Finteech Social Network idea**

### ISSUE THREAD

**Issue by Garudarao** [wise-foundation/wise-website-bug-reports#13]
**Is your feature request related to a problem? Please describe.**
	Fintech Social Network: - As the name suggests the portal will provide social identity and financial identity to all netizens. This can be achieved by giving a Id for social representation and reverse of the ID can be used as payment gateway or wallet with associated telephonic and email and chat ids in various variations of the same id by splitting and reversing it through an app. This provides single id to socialize or advertise, make online or offline payments and communicate
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by coffee-converter** [comment]
We have no need for this, but thanks.
