### ISSUE TITLE
 [BUG] **Type a descriptive title here**Unable to clain wise token. I reserved for 1.04 ETH .  Through the site https://wisetoken.net/reservations I made reservations to obtain Wise Token   However the system does not allow me to claim the tokens ( the link with MetaMask is in place but does not seem to respond) It looks has I have paid a lot ( 1.04 ETH)  to receive only 2.482 WISE

### ISSUE THREAD

**Issue by Verhanneman** [wise-foundation/wise-website-bug-reports#15]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by coffee-converter** [comment]
First try resetting metamask within its advanced settings page, and try your Claim again.  Let me know if that works.

**Comment by Verhanneman** [comment]
Hi It did work 
I removed METAMASK from chrome and re installed it and finally I was able to claim the wise tokens
Many thanks
    On Tuesday, 5 January 2021, 15:02:04 GMT, Coffee Converter <notifications@github.com> wrote:  
 
 


First try resetting metamask within its advanced settings page, and try your Claim again. Let me know if that works.

**Comment by coffee-converter** [comment]
> Hi It did work  I removed METAMASK from chrome and re installed it and finally I was able to claim the wise tokens Many thanks On Tuesday, 5 January 2021, 15:02:04 GMT, Coffee Converter <notifications@github.com> wrote: First try resetting metamask within its advanced settings page, and try your Claim again. Let me know if that works. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Great, my pleasure!
