### ISSUE TITLE
Referral bonus from token reservation not received

### ISSUE THREAD

**Issue by thomasmatty** [wise-foundation/wise-website-bug-reports#16]
Hello,

I have just realized, that I have not received 10% bonus from token reservation of my referral(s). My refferal(s) gets it (invested 0,05 eth to some days (and saw 0,55 eth invested) but I should get bonus too. I only got 0,05 eth equivalent (approx 200 WISE tokens) as my refferal(s) invested more then 1 ETH.

We have probably invested to different reservation days, can be this the issue? Was the 10% bonus for referrer calculated only in case that they both invested to same reservation days? If this is the case it is not described in documentaion and I could get 10% more tokens from referral reservations.

Thanks
Best regards
Thomas

**Comment by coffee-converter** [comment]
If you email me the addresses in question I will take a look.  My email is coffee.becomes.code@gmail.com

**Comment by coffee-converter** [comment]
Closing, as this is normal.  The white paper has details on the reservations bonus structure (https://wisetoken.net/teal/index.html#sec-2-2-3-1).

Less than 1 eth referred = no bonus. 
1-49.99999999 eth referred = 0.05 eth bonus. 
50+ eth referred = 10% of the eth as a bonus.
