### ISSUE TITLE
lost my wise

### ISSUE THREAD

**Issue by thynop508** [wise-foundation/wise-website-bug-reports#17]
i just lost my wise tokens it was taking so long to stake and it still said it was still processing and when i clicked on it to cancel it said i wouldnt be penalized but now all of a sudden i lost all the coins can you get back to me asap

**Comment by coffee-converter** [comment]
If you email me your wise address I can investigate.  My email is coffee.becomes.code@gmail.com

**Comment by coffee-converter** [comment]
This stake was created, then ended on its first active day, thus had a 90% penalty.  Closing this.
