### ISSUE TITLE
Do not succeed claiming my reserved WISE tokens

### ISSUE THREAD

**Issue by johanvanhoorde** [wise-foundation/wise-website-bug-reports#18]
I have reserved 1070 WISE tokens. When I push the button "Claim WISE tokens", nothing seems to happen. I have created the WISE token wallet in my metamask account, but they there are no WISE tokens. 
![WiseSharedScreenshot](https://user-images.githubusercontent.com/77265451/104156928-652f8d80-53ea-11eb-930d-6386dfa83dec.jpg)
![image](https://user-images.githubusercontent.com/77265451/104157076-b770ae80-53ea-11eb-8945-005b3de91dd0.png)
![image](https://user-images.githubusercontent.com/77265451/104157138-dcfdb800-53ea-11eb-82f3-fddc5d07f5d6.png)

**Comment by coffee-converter** [comment]
Looking at your address on etherscan, it looks like you were able to successfully claim your WISE shortly after opening this ticket.  Closing this.
