### ISSUE TITLE
[BUG] **Type a descriptive title here**

### ISSUE THREAD

**Issue by Komtdategen** [wise-foundation/wise-website-bug-reports#19]
Hello,

I am keep getting stuck after taking a 25$ gas fee with metamask to stake max coins for 2 years.
I have enough ETH left for costs.
Could you please help me, since the 13th is getting closer.
Thank you in advance.
![image](https://user-images.githubusercontent.com/77361888/104376398-3f5ad380-5525-11eb-9a1e-515930a64166.png)
[printscreen wise.docx](https://github.com/wise-foundation/wise-website-requests/files/5804880/printscreen.wise.docx)

**Comment by coffee-converter** [comment]
Is there a tx pending on your address on etherscan?

**Comment by Komtdategen** [comment]
I'm sorry, relatively new at crypto world, could you tell me where to find that exactly please?

**Comment by Komtdategen** [comment]
![image](https://user-images.githubusercontent.com/77361888/104377326-a1680880-5526-11eb-8a29-2e6594d26785.png)

**Comment by coffee-converter** [comment]
Try resetting your metamask account in Settings -> Advanced -> Reset Account

**Comment by Komtdategen** [comment]
Ty very much for this simple, but effective and fast answer. Best of 
luck with the project.
