### ISSUE TITLE
[BUG] **referral page does not populate referrals that have staked using my link**

### ISSUE THREAD

**Issue by richtran85** [wise-foundation/wise-website-bug-reports#20]
**Describe the bug**
referral page does not list in detail the staked wise that my referrals have staked. It does show I have reached CM status however.

**To Reproduce**
1. Go to 'https://wisetoken.net/refer'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows
 - Browser [e.g. chrome, safari] firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by coffee-converter** [comment]
@richtran85 I can look in more detail if you want to email me the ETH addresses in question (referrer, referee).  My email is coffee.becomes.code@gmail.com

**Comment by richtran85** [comment]
My wallet address is: 0xca3e1d7862a99f541c3249a4243b8d189a6cd3ca

**Comment by richtran85** [comment]
Says I've reached CM status, but also says I don't have any referred
stakes at the moment.

**Comment by coffee-converter** [comment]
@richtran85 which stakes are not showing up?  I'd need stake IDs or the staker's address to look into it.  If the stakes are less than 365 days, you don't get CM shares for those, so they won't show up there.

**Comment by richtran85** [comment]
0x5fcc7081834bf329d51b7bc95fc1b71f

Here is one, waiting to get others from friends

**Comment by coffee-converter** [comment]
That stake was the last one you referred before reaching CM status one the next one (0xf42acaed5971410917d1d08ecb4e3014), so it didn't earn you CM shares.  Any 365+ day stakes referred from that point on will earn CM shares.

**Comment by coffee-converter** [comment]
Closing for now, please re-open if you find a stake that isn't showing up but should be.
