### ISSUE TITLE
Transactions not completing and transactions disappearing from Etherscan

### ISSUE THREAD

**Issue by forexninja** [wise-foundation/wise-website-bug-reports#22]
**Describe the bug**
I've tried to buy Wise token three times today adn each transaction just disappears The Uniswap interface says it's submitted, but if I attempt to view the transaction on ETherscan it shows "Sorry, We are unable to locate this TxnHash"
This has also been happening to transactions  for the past five days when I've been trying  to stake my existing Wise tokens to take advantage of the original share price.
Some of Transaction Ids that have disappeared
TX Id 0x4bfd3a8411c58aab234799c3910c0866c42409832b0b3b03d51597a84514496b
TX Id 0x25930b2575bc40fa44787045a3e4584f20683d430d5dfb266f674c0877dbc85e
TX Id 0xc0f20ba26c25555d1b73ca0f0af3b372a602040dcffdba85b2340b5aa98ed66f

**To Reproduce**

**Expected behavior**
Wise tokens to get purchased and existing tokens to get staked

**Desktop (please complete the following information):**
Windows 10
Chrome
MetaMask Wallet

Regards,
Jim McCann

**Comment by coffee-converter** [comment]
@forexninja in general for metamask issues like this. the first thing to try is usually "Reset Account" within Metamask's Advanced Settings page.  Give that a try, they try your transactions again.
