### ISSUE TITLE
[BUG] **Stake Not Going Through**

### ISSUE THREAD

**Issue by Mathtodon** [wise-foundation/wise-website-bug-reports#24]
**Describe the bug**
When I submit a stake, the "Staking In Progress" text shows up but never finishes. I've clicked on the "View Transaction" button but when get redirected I get a "Sorry, We are unable to locate this TxnHash" text on the screen. I've tried this with multiple staking values and durations but it never seems to work.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version:

**Comment by coffee-converter** [comment]
@Mathtodon try first clicking the "Reset Account" within Metamask's Advanced Settings page.  Then try your transaction again.
