### ISSUE TITLE
Metamask window.web3 API

### ISSUE THREAD

**Issue by thomasmatty** [wise-foundation/wise-website-bug-reports#25]
Hello, Metamask started to noticed this info when connected to wisestaking.net "We noticed that the current website tried to use the removed window.web3 API. If the site appears to be broken, please click here for more information.
(this is site from the link https://metamask.zendesk.com/hc/en-us/articles/360053147012 )
Is that safe to create new stake with this error now? Are you going to fix that? When?

Thanks
Thomas

**Comment by coffee-converter** [comment]
@thomasmatty this was fixed in the latest release of the website.
