### ISSUE TITLE
USD staking

### ISSUE THREAD

**Issue by GerrySmile** [wise-foundation/wise-website-bug-reports#26]
Hi,

For non-crypto investors it's a bridge too far to buy ETH somewhere on an exchange and send it to Metamask which they have to create themselves

Whuy not connect Paypal, Skrill or Neteller and let them stake with USD, 
Let WISETOKEN itself connect the shares to an ETH wallet or a vault like with the insurance stakes, 
so they get easily connected with their USD account

greetings
Gert

**Comment by coffee-converter** [comment]
Thanks for your comment, but we want to avoid setting up centralized systems like this.
