### ISSUE TITLE
[BUG] The staking calculator on the new web site, appears to be returning over inflated estimates for "Estimated Total Return".

### ISSUE THREAD

**Issue by rohingosling** [wise-foundation/wise-website-bug-reports#27]
**Describe the bug**
The staking calculator on the new web site, appears to be returning over inflated Wise estimates for "Estimated Total Return".

**To Reproduce**
1. Go to the staking calculator on the new website.
2. Click on "Calculate Staking Rewards".
3. Enter 10,000 Wise in the Staking Amount text box.
4. Enter 1 day in the Staking Duration text box.

**Expected behavior**
- One would expect an estimate for "Estimated Total Return" of around ± 10,050 Wise for ~90,909 shares, or there about.
- However, the result the staking calculator gives for "Estimated Total Return" is 11,112.63 WISE, which seems too high for a 10,000 Wise stake of 1 day and 90,909.09 shares.

**Screenshots**
See screen shot attached.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Google Chrome, Version 88.0.4324.104 (Official Build) (64-bit)
 
 
![Wise Staking Calculator Bug](https://user-images.githubusercontent.com/13208833/106513442-aabc1380-64db-11eb-8d39-2c8eb324c7c2.JPG)

**Comment by WiseGuyCrypto** [comment]
The rewards are also underestimated for long stakes (>3 years) 
For example, rewards for a 5000-day stake of 100 WISE are estimated at only 140.19 WISE

**Comment by coffee-converter** [comment]
Fixed in a recent release.
