### ISSUE TITLE
[FEATURE] **Type a descriptive title here**

### ISSUE THREAD

**Issue by RC-Crypto** [wise-foundation/wise-website-bug-reports#28]
would be great if WISE can be backed up on a hardware wallet so it is not on a soft wallet and therefore vulnerable to theft.
I have checked Ledger wallet and many others not any of them support WISE.

**Comment by coffee-converter** [comment]
@RC-Crypto Wise can be stored on hardware wallets.  Many of us already use trezor and ledger for our Wise holdings and stakes.  Check in telegram or discord for help on using hardware wallets.
