### ISSUE TITLE
[BUG] Staking rewards calculator window shakes

### ISSUE THREAD

**Issue by WiseGuyCrypto** [wise-foundation/wise-website-bug-reports#29]
**Describe the bug**
The staking rewards calculator on the home page moves very quickly between two different positions when opened. It appears to be shaking and everything is blurry. 

**To Reproduce**
1. Go to https://wisetoken.net/
2. Click on Calculate Staking Rewards
3. See error

**Expected behavior**
The window should not shake.

**Screenshots**
It's not possible to take a screenshot because it just shows the window in one of two positions. To the human eye, the window is shaking.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 88.0.4324.104 

**Additional context**
N/A

**Comment by coffee-converter** [comment]
Fixed in latest deployment.
