### ISSUE TITLE
 [BUG] **Use team referal adress  "Self referal detected"**

### ISSUE THREAD

**Issue by oktets** [wise-foundation/wise-website-bug-reports#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by coffee-converter** [comment]
@oktets - this message means that you've tried to do a reservation from the same address as the one in the referral link you most recently clicked.  Same-address self-referrals aren't allowed by the contract.
