### ISSUE TITLE
Reopening issue: Referral not showing up

### ISSUE THREAD

**Issue by richtran85** [wise-foundation/wise-website-bug-reports#35]
My wallet ID: 0xCa3E1D7862A99F541C3249A4243b8D189A6cd3CA

Missing the following referrals:
0x5fcc7081834bf329d51b7bc95fc1b71f     (1 year stake)
0xd4a75824b295999dea52a67c861129dc    (3 year stake)
0x469c8e8066423436c90cd51495544ba4   (5 year stake)

Page indicates I've earned CM status, but doesn't show I have any referrals at all.

**Comment by coffee-converter** [comment]
These were your first three referred stakes, which didn't yet give you CM status (less than 10k DAI equivalent in total).  The next referred stake was the one that gave you CM status, but wasn't 365+ days in length, thus doesn't generate CM shares.  Same goes for the other two referred stakes after that (less than 365 days).  

This is working as designed and documented.
