### ISSUE TITLE
[FEATURE] **Integrate password / 2FA for an extra layer of security**

### ISSUE THREAD

**Issue by carlicalle** [wise-foundation/wise-website-bug-reports#36]
**Is your feature request related to a problem? Please describe.**
Unfortunately hackers got my privatkey of my wallet. 
My funds are staked on your platform, now it is probably just a matter of time untill they find out and unstake my WISE Tokens.
Would be great if there was another security layer where you have to log in and not only connecting the wallet through Metamask is enough. 

**Describe the solution you'd like**
Password + Username Login or 2FA Google Authenticator. 

**Describe alternatives you've considered**
There is no alternative. 

**Additional context**
Thank you for your work.

**Comment by coffee-converter** [comment]
A centralized username/password system would only add security risks.  The preferred way to use Metamask is with a hardware wallet, so that the private keys are never online and never vulnerable.
