### ISSUE TITLE
Connect with MetaMask button

### ISSUE THREAD

**Issue by JR2A** [wise-foundation/wise-website-bug-reports#4]
**Describe the bug**

**To Reproduce
1. Go to web page on mobile device
2. Click on Navigation menu
3. Scroll down to "Connect with MetaMask
4. Nothing happens does not give option to connect and does not connect. Same problem when trying to connect to MetaMask in the "Reserve Token" feature. 

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 14.2
 - Browser Tried Safari, Bing and Google
 - Version 

**Additional context**
If this cannot be fixed can you let me know the best way to reserve Wise using mobile device. 
Thank you, Jeff

**Comment by coffee-converter** [comment]
@JR2A to connect to metamask on mobile, you need to use the metamask app's internal browser.

**Comment by JR2A** [comment]
Got it....maybe :)

**Comment by vm06007** [comment]
please use this app on your mobile device:

https://apps.apple.com/us/app/metamask/id1438144202
https://play.google.com/store/apps/details?id=io.metamask&hl=en&gl=US
