### ISSUE TITLE
[BUG] **No reservation after transferring BNB**

### ISSUE THREAD

**Issue by Bodi0** [wise-foundation/wise-website-bug-reports#42]
Hi there! I just made a reservation over 5 BNB (with mode 02) for the new BSC Wise. Unfortunally the BNB spent is not viewable on the reservation plattform even though I sent the 5 BNB. Could you please check? Thx!
Transaction hash on the BSC: 0xa617ad118c961ac466b910f1f81d7e64fdc314fc2f061f9c4ccb8dd7e8a671ec

Kind Regards
Lukas

**Comment by coffee-converter** [comment]
First ensure your metamask is connected to the BSC network, and connected to the same address you reserved from.  Reload the page and see if it still shows 0 WISE.

**Comment by Bodi0** [comment]
It looks perfect now, looks like it just needed some time. Sorry!
