### ISSUE TITLE
[BUG] **Type a descriptive title here**

### ISSUE THREAD

**Issue by Thiaguhh** [wise-foundation/wise-website-bug-reports#46]
I have a wisetoken.net woth the address: 0x62410cc33c1db8ee73edc74c533b8c9c37d7e054
And now it don't have any value, WHy ?

**Comment by coffee-converter** [comment]
@Thiaguhh that's not the official Wise Token, that's something else.  The official Wise Token is https://etherscan.io/token/0x66a0f676479cee1d7373f3dc2e2952778bff5bd6
