### ISSUE TITLE
Cannot trace wise tolens

### ISSUE THREAD

**Issue by CarlitoTrading** [wise-foundation/wise-website-bug-reports#47]
Hello,
I used to have +/- 5700 wise on the staking platform.
I believe staking ended in JAn. When I logged in however and connceted via Metamask I could not see my wise tokens.
Can you tell me where they are available now.
Many thanks in advance
Karel.spiritus@telenet.be

**Comment by vm06007** [comment]
what is your wallet address?

**Comment by CarlitoTrading** [comment]
Hello,
Could trace it.
Have another question however.
My staking is finished and only option seems to transfer my wise balance now to metamask.
But ethereum gas fees seems very high.
Has a big impact on return.
Is this correct?
-Is next step transfer to metamask via eth network?
- what if i would mike to stake agzin? First transfer also via metamask
Not do vlear to me
Regards
Karel

**Comment by vm06007** [comment]
Yes this is correct
