### ISSUE TITLE
i cant connect meta mask to wisetoken.net

### ISSUE THREAD

**Issue by Toast-ux** [wise-foundation/wise-website-bug-reports#49]
**Describe the bug**
i cant connect meta mask to wisetoken.net

**To Reproduce**
1. Go to 'wisetoken.net'
2. Click on 'connect wallet'
4. Scroll down to 'nothing happens'
5. See error 

**Expected behavior**
normally my wallet connects and shows my staked wise token balance 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [N/A]
 - Browser [Brave browser]
 - Version [N/A]

**Additional context**
on meta mask it shows connected to website but its not showing connected on wisetoken.net
colekramer@rocketmail.com

**Comment by vm06007** [comment]
Should be resolved now
