### ISSUE TITLE
Supply from 3ETH on the wise lending cannot find it.

### ISSUE THREAD

**Issue by WimNoel** [wise-foundation/wise-website-bug-reports#52]
**Describe the bug**
On 1 sept i did supply 3ETH on the wise lending. My supply position was already 0.5€ at that moment. But the 3 €were not added.
So can you tell me where they are located

My wallet :
0x2a6a05755F32279EA600874a80498fe532c62F48
transaction id 
0x9dfb7aca988f5cbf9424284fde38301350144a01290dd75ff904c1d971b15162

**Comment by vm06007** [comment]
Please send DM here to resolve: https://twitter.com/EthVitally
