### ISSUE TITLE
Display globals as ticker/header on app.wisetoken.net

### ISSUE THREAD

**Issue by Tim-TheToolmanTaylor** [wise-foundation/wise-website-bug-reports#54]
In past variations of the site, there used to be a header that showed globals like the latest shareprice. I found these very helpful to demonstrate to users the gradual increase in share price, and how that should effect your staking strategy. 
Would we please be able to add back a header like this?:
![image](https://github.com/wise-foundation/wise-website-requests/assets/156102782/b2372576-8cbc-4b1c-84ae-4fcc5d4864e2)

I believe the call should be a simple call to the WISE token address `0x66a0f676479Cee1d7373f3DC2e2952778BfF5bd6`
And would be something like
`{totalStaked, totalShares, totalShareprice} = WiseToken.globals()`

We can be more granular one day to show the amount staked in a given period, but I think having a graphic that also showed the % increase in share price on that wise day was a very helpful metric and would be nice to have.

Not a high priority, but I think it would make for a nice enhancement.

**Comment by vm06007** [comment]
Hello @Tim-TheToolmanTaylor, I'd like to notify you that this header is still available and you should be able to see it.
It is in user preferences currently and you can toggle if you want to see it or not (user preference icon is located on the sidebar at the very bottom, gear icon) 

once clicked you should b able to see prefernces: try to toggle `Show Global Statistic` to enable the header

![Screenshot 2024-01-10 at 3 31 05 PM](https://github.com/wise-foundation/wise-website-requests/assets/1138692/bee387a9-9cad-4090-be9b-ae974259e92c)

Thanks!

**Comment by Tim-TheToolmanTaylor** [comment]
Thank you @vm06007 - I completely missed that! 
This is great news, thanks for clarifying!
