### ISSUE TITLE
[BUG] * unable to unstake my WISE from app.wisetoken.net

### ISSUE THREAD

**Issue by midas81** [wise-foundation/wise-website-bug-reports#55]
I connect my metamask wallet to app.wisetoken.net and click on stakes and there is no stakes showing up. It says I have no stakes. I still have a stake that ended in January and need to claim my WISE. This is the same wallet that I used to create the stake. This is also using the same hardware with the same configuration as before. I tried using metamask on Chrome (version 122.0.6261.112) and (version 87.0.4280.88) to access with no luck. It also looks like the chat support option for that site is no longer supported. Please advise.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vm06007** [comment]
Probably you've used different wallet address
