### ISSUE TITLE
[BUG] **out of date**

### ISSUE THREAD

**Issue by SvenBell** [wise-foundation/wise-website-bug-reports#6]
**Describe the bug**
WISE will REFUND up to 70% of your gas fees for the first 20,000 ETH sent to the contract (current balance: 45,744 ETH)
Banner is out of date and irellevent and potentially misleading.

**To Reproduce**
load main web page of web site
**Expected behavior**
Up to date content, their is no longer a refund of gas fees, it's over as of 20,000 ETH.

**Comment by coffee-converter** [comment]
Thanks, yep this banner will eventually have something else in it.
