### ISSUE TITLE
[BUG] unable to reserve wise due to payment method being grayed out

### ISSUE THREAD

**Issue by danitorres55** [wise-foundation/wise-website-bug-reports#7]
**Describe the bug**
I am unable to reserve wise tokens if metamask wallet has not funds. The payment method drop down is grayed out. 

**To Reproduce**
1. Go to 'wisetoken.net'
2. Click on 'Metamask' add on or 'Connect with Metamask' button at the top of the page
3. Login to Metamask
4. Click on 'Buy' to purchase ethereum and fund account
5. Click on 'Continue to Wyre'
6. Enter amount you'd like to purchase

**Expected behavior**
Payment method should be a selectable field or there should be guidance on how to connect Wyre to Metamask in order to fund account.

**Actual behavior**
Payment method is grayed out. 

**Workaround**
Funding the Metamask wallet directly allowed me to reserve wise tokens. Someone less technical however would probably give up because there isn't much info on the web and I wasn't able to find any directly related to the issue I was experiencing. If the only way to fund account is by having funds in Metamask, then there should be some help tips or info somewhere on the page that informs the user.

**Screenshots**
 
<img width="417" alt="wise" src="https://user-images.githubusercontent.com/76568950/103104636-6d1fbd00-45f6-11eb-9225-7dcd576db88a.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser Firefox, Chrome and I.E
 - Version Firefox 84, Chrome 87, I.E. 87

**Smartphone (please complete the following information):**

**Additional context**
I've seen youtube vidoes where users have multiple different options to fund metamask account such as coinbase. I was only able to see Wyre and direct deposit. I tried connecting my metamask account to coinbase to see if that would change my options but it did not.

**Comment by coffee-converter** [comment]
@danitorres55 that page is from Wyre, not the wisetoken site itself.  We can't control how their interface works.  You can open an issue with Wyre and/or Metamask about this.
