### ISSUE TITLE
Entry of 0.50 eth failed on day 44

### ISSUE THREAD

**Issue by xmtyumurg** [wise-foundation/wise-website-bug-reports#8]
Hello, on the 44th I made a deposit of 0.50 eth that was never validated, it was deducted from my wallet. Then the day closed and my money stayed there because the eth confirmation time is higher and is still pending.
I would not like to lose those 0.5, please if you can help me. I leave you here all the data.

Transaction Hash:
0x14adb10d04cdc06f5cb9a3e06583f11f270bc8811d13e9592c356ec233d64c63 
Status:
 Pending
Block:
(Pending)
Time Last Seen:
00 days 00 hr 26 min 26 secs ago (Dec-24-2020 11:46:00 PM)
Estimated Confirmation Duration:
> 2 hrs |  Gas Tracker
From:
**0xd7dbcc5e9412db6fdce1893c1566eabd434ad459**   
To:
Contract 0xfef0d2f3a79b4338d8418003dd9df89281242063 
Value:
0.5 Ether ($305.48)
Max Txn Cost/Fee:
0.00358908 Ether ($2.19)
Gas Price:
0.000000033 Ether (33 Gwei)

My eth wallet is the following one, which I have registered with a wise token
0xd7DBCc5e9412Db6FDcE1893C1566eABD434AD459

**Comment by coffee-converter** [comment]
You won't lose the eth.   
You can either cancel it in metamask, or let it fail on its own.
