### ISSUE TITLE
Unable to connect my Metamask account with Wise sit

### ISSUE THREAD

**Issue by Royrina** [wise-foundation/wise-website-bug-reports#9]
**Describe the bug**
When trying to connect my Metamask account, the site is kept on reloading.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, safari]: ****Crome Extention****

**Additional context**

**Comment by coffee-converter** [comment]
Please fill out the requested info about your device and browser.  I can't help much without that info.

**Comment by coffee-converter** [comment]
@Royrina please fill out the requested info or close this, thanks.

**Comment by coffee-converter** [comment]
Closing this.  If you want to reopen a new bug report for this, please fill out the requested info on it.
